is_debug: $IS_DEBUG

# joplin uses uuid without hyphens
# leave empty to pick random auto value
app_id: $APP_ID

# note id for auto update
note_id: $NOTE_ID

# parent id for list source data
parent_id: $PARENT_ID

# joplin s3 sync storage
s3:
  host: $S3_HOST
  key: $S3_KEY
  secret: $S3_SECRET
  bucket: $S3_BUCKET
  region: $S3_REGION

# joplin web clipper api
web_clipper:
  host: $WEB_CLIPPER_HOST
  token: $WEB_CLIPPER_TOKEN
